services:
  db:
    image: mysql:8.0
    container_name: task-manager-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:7.0-alpine
    container_name: task-manager-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: task-manager-redisinsight
    restart: always
    environment:
      - REDISINSIGHT_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/usr/src
    networks:
      - backend
  prometheus:
    image: prom/prometheus
    container_name: task-manager-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - backend
  grafana:
    image: grafana/grafana
    container_name: task-manager-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - backend
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/redis
      o: bind
  redisinsight_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/redisinsight
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/grafana
      o: bind
networks:
  backend:
    driver: bridge
